### ISSUE TITLE
Reference paper of  Bezier-AvoidanceClusted

### ISSUE THREAD

**Issue by BenjyWP** [biagio-trimarchi/Bezier#1]
Could you please share the reference paper of the Bezier-AvoidanceClusted which gives outstanding results?

**Comment by biagio-trimarchi** [comment]
Hi, currently there is not a paper written on this work. I can share with you some of the papers which I took inspiration from if you are interested.

**Comment by BenjyWP** [comment]
Millions of thanks for your kindness. Yes, i am very interested in this
work  and looking forward to your sharing. :-) The path planning using
Bézier curves would be one of my upcoming research topics. It is my great
pleasure to follow your codes in GitHub.

**Comment by biagio-trimarchi** [comment]
I apologize that I kept you waiting, github did not notify me your answer.

I suggest as a reference for Bezier/Bernstein curves the following review:
https://www.sciencedirect.com/science/article/pii/S0167839612000192

And this little note:
https://d1wqtxts1xzle7.cloudfront.net/49392061/Bernstein-Polynomials-libre.pdf?1475737086=&response-content-disposition=inline%3B+filename%3DGeometric_Modeling_Notes_BERNSTEIN_POLYN.pdf&Expires=1673982237&Signature=WmS6HhKwzlzSUjwXFasd769t4NFyk~M3fBTGIP~mzOnxXn0c8VjoiT5Ekgzq3MNv31dLv7ef9PuwzADKZsx3ESZiKFR7Q3f6JrYCb2CLmLXjzhFDYXDBri8kBMNjSjtTpsHYkrd0axoCkjXoQA1kalcYKBsH08Rm2w1X41HwoGg9wnrHtAB~o~CvinLSffup2mM2z4ZpQhTGxQFyxUeWCn5zUNB9IxtlGJZuudOzv9PNpwTYHlPcam--c4silmRQmNMfJfEjKWINkLDQ4Mc1mddxbvDq0j1ScuBFxt97RFyoT5i~LE~QPR30yWswfdN~NcaMtC3pFoubkmFBd0Mh9A__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA

Another good resource was this Master Thesis:
https://core.ac.uk/download/pdf/158318074.pdf

My work was strongly influenced by this 2 papers (and by the other works of the same authors):
https://arc.aiaa.org/doi/full/10.2514/1.G001531
https://arc.aiaa.org/doi/abs/10.2514/6.2015-0598

And also this paper:
https://arxiv.org/abs/2109.09041

Are you a researcher/PhD student?

**Comment by BenjyWP** [comment]
Glad to receive your kind reply.

 I am now a researcher focusing on the motion control of UAVs and working
to involve distributed path planning for some space and time requirements.
Collision avoidance with moving obstacles and neighbor UAVs is my research
interest.

Your sharing has inspired me a lot, especially the master thesis providing
a detailed introduction to the code in your github.

May you have good health and happiness.

Biagio Trimarchi ***@***.***> 于2023年1月18日周三 02:11写道：
